Repository planetarium/9c-rudolf, pull requests merged in 2023-11, with the labels that each got.

#40 PDX-25: Correct some incorrect usages
  src/esm_bypass_global.ts
  src/main.ts
  src/tx/action.service.ts
  src/tx/tx.constants.ts
  src/tx/tx.service.ts
Labels: Extra Small

#41 PDX-28: Request bearer token for POST endpoints
  prisma/migrations/20231102030335_create_auth_token/migration.sql
  prisma/schema.prisma
  src/common/decorators/required-auth-token.decorator.ts
  src/common/guards/auth.guard.ts
  src/job/job.controller.ts
Labels: Extra Small

#42 Provide `jobSequence` field at `/jobs/{id}` endpoint
  src/job/job.controller.ts
  src/job/job.service.ts
Labels: Extra Small

#44 Configure some variables from environment variables
  src/queue/queue.service.ts
Labels: Extra Small

#45 PDX-51: except /metrics api on prometheus counter
  src/http-response.middleware.ts
Labels: Extra Small

#46 Import ConfigModule at QueueModule
  src/queue/queue.module.ts
Labels: bug

#48 PDX-86: make NCG_MINTER nullable
  src/tx/tx.constants.ts
Labels: Extra Small

#49 fix HttpResponseMiddleware url to baseUrl
  src/http-response.middleware.ts
Labels: Extra Small

#47 PDX-79 add @IsTicker validator on CreateClaimItemsDto.Item.ticker
  src/job/dto/create-claim-items.dto.ts
  src/job/dto/create-transfer-assets.dto.ts
  src/utils/currency.ts
Labels: Extra Small

#50 🔨 PDX-109: Correct initial labelNames for metrics
  src/app.module.ts
Labels: bug

#51 PDX-113: Add IsDefined validator on dto
  src/job/dto/create-claim-items.dto.ts
  src/job/dto/create-transfer-assets.dto.ts
Labels: Extra Small

#52 PDX-112: Bump version transfer_assets
  src/tx/action.service.ts
Labels: Extra Small

#54 PDX-114: add ticker whitelist model to prisma
  prisma/migrations/20231115062915_add_ticker_whitelist/migration.sql
  prisma/schema.prisma
  src/job/job.service.ts
Labels: Extra Small

#55 set currency of claimItem to contants if it exists
  package.json
  prisma/migrations/20231116064121_alter_amount_to_string/migration.sql
  prisma/schema.prisma
  src/job/dto/create-claim-items.dto.ts
  src/job/dto/create-transfer-assets.dto.ts
  src/tx/action.service.ts
  src/tx/tx.constants.ts
  yarn.lock
Labels: Small

#56 Set `Decimal.set({ toExpPos })` globally
  src/main.ts
Labels: bug, Extra Small

#57 PDX-162: add remaining and failed jobs gauge
  src/queue/queue.cron.ts
  src/queue/queue.module.ts
  src/queue/queue.service.ts
Labels: Extra Small

#58 PDX-172: add total jobs metric
  src/queue/queue.cron.ts
  src/queue/queue.module.ts
  src/queue/queue.service.ts
Labels: Extra Small

#59 PDX-167: make job status inquire to use lastTxStatus
  src/job/job.service.ts
  src/transaction/transaction.service.ts
Labels: Extra Small
