Repository planetarium/9c-rudolf, pull requests merged in 2023-10, with the labels that each got.

#1 Add api: POST /jobs/claim-items
  package.json
  prisma/migrations/20231004005556_alter_job/migration.sql
  prisma/schema.prisma
  src/app.module.ts
  src/job/dto/create-claim-items.dto.ts
  src/job/job.controller.ts
  src/job/job.module.ts
  src/job/job.service.ts
  src/main.ts
  yarn.lock
Labels: Small

#3 Add api: GET /jobs/:id
  src/app.module.ts
  src/job/job-status.entity.ts
  src/job/job.controller.ts
  src/job/job.service.ts
  src/transaction/transaction.controller.ts
  src/transaction/transaction.module.ts
  src/transaction/transaction.service.ts
Labels: Small

#2 Add api: POST /jobs/transfer-assets
  src/app.module.ts
  src/job/dto/create-transfer-assets.dto.ts
  src/job/job-status.entity.ts
  src/job/job.controller.ts
  src/job/job.service.ts
  src/transaction/transaction.controller.ts
  src/transaction/transaction.module.ts
  src/transaction/transaction.service.ts
  src/utils/currency.ts
Labels: Medium

#15 Rename secret variable name
  .github/workflows/push_docker_image.yaml
Labels: bug

#16 Setup docker buildx driver
  .github/workflows/push_docker_image.yaml
Labels: bug

#17 Make push_docker_image workflow work
  .github/workflows/push_docker_image.yaml
Labels: bug

#18 Complete push_docker_image workflow
  .github/workflows/push_docker_image.yaml
Labels: bug

#19 Correct multiline script
  .github/workflows/push_docker_image.yaml
Labels: bug

#24 Fix Docker image
  Dockerfile
Labels: bug

#28 Give up alpine image
  Dockerfile
Labels: bug

#32 Fix `JobService.claimItems` bug
  src/job/job.service.ts
Labels: bug

#35 fix sign with kms digest mode
  .gitignore
  .yarn/patches/@planetarium-account-aws-kms-npm-3.5.0-97a98b815e.patch
  .yarn/patches/@planetarium-tx-npm-3.4.0-d26f037477.patch
  .yarn/releases/yarn-3.6.4.cjs
  .yarnrc.yml
  package.json
  src/tx/tx.service.ts
  yarn.lock
Labels: bug

#34 Update README
  README.md
Labels: documentation

#38 add prometheus
  package.json
  src/app.module.ts
  src/http-response.middleware.ts
  src/main.ts
  yarn.lock
Labels: Extra Small

#39 Bump `@planetarium/*` package related to KMS signing
  .yarn/patches/@planetarium-account-aws-kms-npm-3.5.0-97a98b815e.patch
  .yarn/patches/@planetarium-tx-npm-3.4.0-d26f037477.patch
  package.json
  src/tx/tx.service.ts
  yarn.lock
Labels: Small
